#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys
import os
import yaml

from importlib import import_module
import configgen
from configgen.Emulator import Emulator, _dict_merge, _load_defaults, _load_system_config
from configgen.emulatorlauncher import launch
from configgen.generators import get_generator
from typing import TYPE_CHECKING, Any
from pathlib import Path

rom = None
if "-rom" in sys.argv:
    rom = sys.argv[sys.argv.index("-rom") + 1]

if "-emulator" in sys.argv:
    emulator_name = sys.argv[sys.argv.index("-emulator") + 1]


def _new_get_generator(emulator: str):
    
    print(f"Selected emulator: {emulator}", file=sys.stderr)    
    print(f"Selected Rom : {rom}", file=sys.stderr)    

    if emulator == 'play':
        from generators.namco2x6.playGenerator import PlayGenerator
        return PlayGenerator()

    if emulator == 'wine':
        from generators.wine.wineGenerator import WineGenerator
        return WineGenerator()    

    if emulator == 'demul':
        from generators.demul.demulGenerator import DemulGenerator
        return DemulGenerator()

    #fallback to batocera generators
    return get_generator(emulator)
    
from configgen.batoceraPaths import DEFAULTS_DIR
configgen.emulatorlauncher.get_generator = _new_get_generator

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    sys.exit(launch())
    